var searchData=
[
  ['dcauchy',['DCauchy',['../classDCauchy.html',1,'']]],
  ['dchisquared',['DChiSquared',['../classDChiSquared.html',1,'']]],
  ['decomplu',['DecompLU',['../classDecompLU.html',1,'']]],
  ['decompqr',['DecompQR',['../classDecompQR.html',1,'']]],
  ['delaunay',['Delaunay',['../classDelaunay.html',1,'']]],
  ['densityestimator',['DensityEstimator',['../classDensityEstimator.html',1,'']]],
  ['detectorglobals',['DetectorGlobals',['../classDetectorGlobals.html',1,'']]],
  ['dexponential',['DExponential',['../classDExponential.html',1,'']]],
  ['dfunction',['DFunction',['../classDFunction.html',1,'']]],
  ['dgaus',['DGaus',['../classDGaus.html',1,'']]],
  ['dmaxwell',['DMaxwell',['../classDMaxwell.html',1,'']]],
  ['dmultigaus',['DMultiGaus',['../classDMultiGaus.html',1,'']]],
  ['dpoisson',['DPoisson',['../classDPoisson.html',1,'']]],
  ['drawingoptions',['DrawingOptions',['../structDrawingOptions.html',1,'']]],
  ['dspiral',['DSpiral',['../classDSpiral.html',1,'']]],
  ['dtfe',['DTFE',['../classDTFE.html',1,'']]],
  ['dtriangular',['DTriangular',['../classDTriangular.html',1,'']]],
  ['duniform',['DUniform',['../classDUniform.html',1,'']]]
];
